
# Fine tuned Smolvlm-256M

##Install library

In [ ]:
!pip install --upgrade transformers accelerate bitsandbytes
!pip install peft datasets opencv-python-headless
!pip install trl
!pip install mlflow dagshub
!pip install jiwer rapidfuzz

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.8.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.14.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.5.0-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.3.5)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.8.0-py3-none-any.whl (10.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.6/10.6 MB 82.7 MB/s eta 0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 23.2 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 32.6 MB/s eta 0:00:00
Downloading huggingface_hub-1.14.0-py3-none-any.whl (661 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.5/661.5 kB 36.3 MB/s eta 0:00:00
Downloading hf_xet-1.5.0-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 92.6 MB/s eta 0:00:00
Installing collected packages: hf-xet, huggingface-hub, bitsandbytes, accelerate, transformers
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.3.0
    Uninstalling hf-xet-1.3.0:
      Successfully uninstalled hf-xet-1.3.0
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.4.1
    Uninstalling huggingface_hub-1.4.1:
      Successfully uninstalled huggingface_hub-1.4.1
  Attempting uninstall: accelerate
    Found existing installation: accelerate 1.12.0
    Uninstalling accelerate-1.12.0:
      Successfully uninstalled accelerate-1.12.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed accelerate-1.13.0 bitsandbytes-0.49.2 hf-xet-1.5.0 huggingface-hub-1.14.0 transformers-5.8.0
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.3)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.12/dist-packages (4.13.0.92)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from peft) (5.8.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.13.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.7.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.24.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.5.0)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers->peft) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->peft) (0.22.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub>=0.25.0->peft) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub>=0.25.0->peft) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub>=0.25.0->peft) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface_hub>=0.25.0->peft) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.20.0->huggingface_hub>=0.25.0->peft) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.20.0->huggingface_hub>=0.25.0->peft) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.20.0->huggingface_hub>=0.25.0->peft) (0.1.2)
Collecting trl
  Downloading trl-1.4.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.13.0)

##Load the model

In [ ]:
import torch
from transformers import BitsAndBytesConfig, AutoModelForImageTextToText, AutoProcessor

model_id = "HuggingFaceTB/SmolVLM-256M-Instruct"
# BitsAndBytesConfig int-4 config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
# Load model and tokenizer
model = AutoModelForImageTextToText.from_pretrained(
    model_id,
    device_map="auto",
    dtype=torch.bfloat16,
    quantization_config=bnb_config,
    _attn_implementation="sdpa" # Use `flash_attention_2` on Ampere GPUs and above and `eager` on older GPUs.
)
processor = AutoProcessor.from_pretrained(model_id)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/513M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/471 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/136 [00:00<?, ?B/s]

processor_config.json:   0%|          | 0.00/68.0 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/429 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/486 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

### We now add LoRA adapters for parameter efficient finetuning - this allows us to only efficiently train 1% of all parameters.

In [ ]:
from peft import get_peft_model, LoraConfig

peft_config = LoraConfig(
    r=16, # Augmenté de 8 à 16 pour mieux capturer les détails
    lora_alpha=32,
    lora_dropout=0.05,
    # On cible plus de modules pour une meilleure "intelligence" sur les reçus
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    use_dora=False,
    init_lora_weights="gaussian"
)


# Apply PEFT model adaptation
peft_model = get_peft_model(
    model,
    peft_config
)

In [ ]:
# Print trainable parameters
peft_model.print_trainable_parameters()

trainable params: 2,727,936 || all params: 259,212,864 || trainable%: 1.0524

##Preparation of data

In [ ]:
# Configuration
image_folder = "/kaggle/input/datasets/ahmadoubg/dataset-receipt/images/"
json_folder = "/kaggle/input/datasets/ahmadoubg/dataset-receipt/dataJSON/"
output_path = "dataset.jsonl"

In [ ]:
import os
import json
from pathlib import Path

def build_dataset(image_folder, json_folder, output_path):

  prompt = (
          "Extract company, date, address and total from this receipt.\n"
          "If missing return null.\n"
          "Do NOT guess.\n"
          "Return ONLY valid JSON."
  )

  with open(output_path, "w") as out_file:
      for img_file in os.listdir(image_folder):
          if not img_file.endswith(".jpg"):
              continue

          base_name = Path(img_file).stem
          json_path = os.path.join(json_folder, base_name + ".json")

          if not os.path.exists(json_path):
              continue

          with open(json_path, "r") as f:
              data = json.load(f)

          # Safe JSON structure
          target = {
              "company": data.get("company", None),
              "date": data.get("date", None),
              "address": data.get("address", None),
              "total": data.get("total", None)
          }

          sample = {
              "img_path": os.path.join(image_folder, img_file),
              "messages": [
                  {
                      "role": "user",
                      "content": [
                          {"type": "image", "image": os.path.join(image_folder, img_file)},
                          {"type": "text", "text": prompt}
                      ]
                  },
                  {
                      "role": "assistant",
                      "content": [
                          {"type": "text", "text": json.dumps(target)}
                      ]
                  }
              ]
          }

          return out_file.write(json.dumps(sample) + "\n")

  print("✅ Dataset ready (jsonl)")

Split the data

In [ ]:
from datasets import load_dataset
data = build_dataset(image_folder, json_folder, output_path)
dataset = load_dataset("json", data_files= data)["train"]

✅ Dataset ready (jsonl)

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
print("Original dataset[0] structure:")
print(dataset[0])

Original dataset[0] structure:
{'img_path': '/kaggle/input/datasets/ahmadoubg/dataset-receipt/images/623.jpg', 'messages': [{'role': 'user', 'content': [{'type': 'image', 'image': '/kaggle/input/datasets/ahmadoubg/dataset-receipt/images/623.jpg'}, {'type': 'text', 'text': 'Extract company, date, address and total from this receipt.\nIf missing return null.\nDo NOT guess.\nReturn ONLY valid JSON.'}]}, {'role': 'assistant', 'content': [{'type': 'text', 'text': '{"company": "B & BEST RESTAURANT", "date": "22/04/2017", "address": "NO.12,JALAN SS4C/5,PETALING JAYA SELANGOR DARUL EHSAN", "total": "22.25"}'}]}]}

In [ ]:
len(dataset)

950

### Preprocess and structure data for fine-tuning

In [ ]:
def process_metadata(example):
    prompt = "Extract company, date, address and total from this image. If missing return null. Do NOT guess. Answer ONLY in JSON."

    full_chat = example["messages"]

    prompt_chat = [example["messages"][0]]

    full_text = processor.apply_chat_template(
        full_chat,
        tokenize=False
    )

    prompt_text = processor.apply_chat_template(
        prompt_chat,
        tokenize=False,
        add_generation_prompt=True
    )

    prompt_len = len(processor.tokenizer(prompt_text)["input_ids"])

    return {
        "img_path": example["img_path"],
        "full_text": full_text,
        "prompt_len": prompt_len
    }

In [ ]:
dataset = dataset.map(
    process_metadata,
    remove_columns=dataset.column_names
)

Map:   0%|          | 0/950 [00:00<?, ? examples/s]

### Convert a list of sample(batch) to a tensor format for training

In [ ]:
from PIL import Image
import torch

def collate_fn(batch):
    valid_images = []
    valid_texts = []
    valid_prompt_lens = []

    # ---------------------------
    # 1. Safe loading (no misalignment)
    # ---------------------------
    for item in batch:
        try:
            image = Image.open(item["img_path"]).convert("RGB")
            valid_images.append(image)
            valid_texts.append(item["full_text"])
            valid_prompt_lens.append(item["prompt_len"])
        except Exception as e:
            print(f"[WARNING] Failed image: {item.get('img_path')} -> {e}")

    if len(valid_images) == 0:
        raise ValueError("All images failed to load.")

    # ---------------------------
    # 2. Multimodal processing
    # ---------------------------
    inputs = processor(
        images=valid_images,
        text=valid_texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=1024  # IMPORTANT: control truncation
    )

    input_ids = inputs["input_ids"]
    labels = input_ids.clone()

    # ---------------------------
    # 3. Mask padding tokens
    # ---------------------------
    pad_token_id = processor.tokenizer.pad_token_id
    if pad_token_id is not None:
        labels[labels == pad_token_id] = -100

    # ---------------------------
    # 4. SAFE prompt masking
    # ---------------------------
    seq_len = labels.shape[1]

    for i, prompt_len in enumerate(valid_prompt_lens):
        # Prevent overflow if truncated
        safe_len = min(prompt_len, seq_len)

        # Mask prompt tokens
        labels[i, :safe_len] = -100

    # ---------------------------
    # 5. Attach labels
    # ---------------------------
    inputs["labels"] = labels

    return inputs

## Evaluation

### evaluation using metrics:

**Accuracy, Recall, Precision, F1 score and CER**

### Configuration for evaluation

In [ ]:
import re
import numpy as np
from jiwer import cer
from rapidfuzz import fuzz

# ---------------------------
# Config
# ---------------------------
FIELDS = ["company", "date", "address", "total"]

WEIGHTS = {
    "company": 1.0,
    "date": 2.0,
    "address": 1.0,
    "total": 3.0
}

FUZZY_FIELDS = ["company", "address"]
EXACT_FIELDS = ["date", "total"]

### Fonctions helpers

In [ ]:
def safe_json_extract(text):
    """Extract JSON safely from model output"""
    try:
        match = re.search(r'\{.*?\}', text, re.DOTALL)
        if match:
            return json.loads(match.group())
    except:
        pass
    return None


def normalize_text(x):
    if x is None:
        return ""
    return str(x).strip().lower()


def is_valid_total(x):
    return bool(re.match(r'^\d+(\.\d{1,2})?$', x))


def is_valid_date(x):
    return bool(re.match(r'^\d{2}[/-]\d{2}[/-]\d{2,4}$', x))


def fuzzy_match(a, b, threshold=85):
    return fuzz.ratio(a, b) >= threshold

### Fonction eval

In [ ]:
def evaluate_sample(gt_str, pred_str):
    # CER global (optional)
    global_cer = cer(gt_str.lower(), pred_str.lower())

    gt_dict = safe_json_extract(gt_str)
    pred_dict = safe_json_extract(pred_str)

    if gt_dict is None or pred_dict is None:
        return {
            "valid_json": 0,
            "accuracy": 0,
            "precision": 0,
            "recall": 0,
            "f1": 0,
            "cer": global_cer,
            "field_cer": 0 # Added to prevent KeyError
        }

    tp, fp, fn = 0, 0, 0
    weighted_correct = 0
    total_weight = sum(WEIGHTS.values())

    field_cers = []

    for field in FIELDS:
        gt_v = normalize_text(gt_dict.get(field, ""))
        pred_v = normalize_text(pred_dict.get(field, ""))

        # --- CER per field ---
        if gt_v and pred_v:
            field_cers.append(cer(gt_v, pred_v))

        match = False

        # --- Matching logic ---
        if field in FUZZY_FIELDS:
            match = fuzzy_match(gt_v, pred_v)

        elif field in EXACT_FIELDS:
            if field == "total":
                if is_valid_total(pred_v):
                    match = (gt_v == pred_v)

            elif field == "date":
                if is_valid_date(pred_v):
                    match = (gt_v == pred_v)

        # --- Metrics update ---
        if gt_v:
            if match:
                tp += 1
                weighted_correct += WEIGHTS[field]
            elif not pred_v:
                fn += 1
            else:
                fp += 1
        else:
            if pred_v:
                fp += 1
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

    weighted_accuracy = weighted_correct / total_weight
    avg_field_cer = np.mean(field_cers) if field_cers else 0

    return {
        "valid_json": 1,
        "accuracy": weighted_accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "cer": global_cer,
        "field_cer": avg_field_cer
     }

### Initialistion of dagshub and mflow for save experiments

In [ ]:
import dagshub
import mlflow

# Remplace par tes vrais identifiants DagsHub
dagshub.init(repo_owner="AhmadouBG", repo_name="smolvlm-receipts", mlflow=True)
mlflow.set_experiment("SmolVLM_Evaluation")

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=b871ccf7-e82f-46db-bf95-59c77de5a56f&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=5bdb721841c50a76db1792284d65717775f4dd789428a258d5569fa90c2c3400

Accessing as AhmadouBG

Initialized MLflow to track repo "AhmadouBG/smolvlm-receipts"

Repository AhmadouBG/smolvlm-receipts initialized!

<Experiment: artifact_location='mlflow-artifacts:/efb26ce8698d413b94f6c81be8257280', creation_time=1778109960292, experiment_id='0', last_update_time=1778109960292, lifecycle_stage='active', name='SmolVLM_Evaluation', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

Before fine tuning, let's check the first example for the model output using 20 sample and 10 sample after fine tuned with unseen data.

In [ ]:
import io
from PIL import Image
import base64

def run_and_log_evaluation(model, dataset_subset, run_name="Evaluation"):
    model.eval()
    all_metrics = []
    json_invalid_count = 0

    with mlflow.start_run(run_name=run_name):
        mlflow.log_params({
            "model_type": "SmolVLM-256M",
            "temperature": 0.0001,
            "status": "post-finetuning" if hasattr(model, "peft_config") else "base"
        })

        for i in range(min(len(dataset_subset), 10)): # Augmenté à 50 pour plus de fiabilité
            example = dataset_subset[i]
            image_pil = Image.open(example['img_path']).convert("RGB")

            # Template propre
            input_text = processor.apply_chat_template([
                {"role": "user", "content": [{"type": "image"}, {"type": "text", "text": prompt}]}
            ], tokenize=False, add_generation_prompt=True)

            inputs = processor(images=image_pil, text=input_text, return_tensors="pt").to("cuda")

            with torch.no_grad():
                outputs = model.generate(**inputs, max_new_tokens=256, temperature=0.0001, do_sample=False)

            # Nettoyage strict
            generated_response = processor.decode(outputs[0], skip_special_tokens=True)
            # On ne garde que ce qui vient APRÈS le prompt
            generated_response = generated_response.split("Assistant:")[-1].strip()
            print("generated_response", generated_response)

            # Extraction de la réponse JSON
            # Extraction GT
            gt_json_str = example['full_text'].split("Assistant:")[-1].replace("<end_of_utterance>", "").strip()

            # Évaluation avec sécurité
            try:
                res = evaluate_sample(gt_json_str, generated_response)
                if not res.get('valid_json', False): json_invalid_count += 1
                all_metrics.append(res)
            except Exception as e:
                print(f"Erreur évaluation index {i}: {e}")

            image_pil.close() # Libérer la RAM

        # Métriques agrégées
        metrics_to_log = {
            "avg_precision": np.mean([m['precision'] for m in all_metrics]),
            "avg_recall": np.mean([m['recall'] for m in all_metrics]),
            "avg_f1": np.mean([m['f1'] for m in all_metrics]),
            "avg_cer": np.mean([m['cer'] for m in all_metrics]),
            "json_failure_rate": json_invalid_count / len(all_metrics) if all_metrics else 1
        }

        mlflow.log_metrics(metrics_to_log)
        print(f"✅ Terminé. F1: {metrics_to_log['avg_f1']:.2f} | JSON Fail: {metrics_to_log['json_failure_rate']:.2%} | CER: {metrics_to_log['avg_cer']:.2f} | Precision: {metrics_to_log['avg_precision']:.2f} | Recall: {metrics_to_log['avg_recall']:.2f}")

In [ ]:
run_and_log_evaluation(model, dataset, run_name="Base_Model_Test")

[transformers] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

generated_response {
    "menu": {
        "nm": "SSTC/5",
        "num": "SSTC/5",
        "num": "PETALING JAYA",
        "price": "001808391968",
        "price_invoice": "21.00"
    },
    "sub_total": {
        "subtotal_price": [
            {
                "subtotal_price": "21.00",
                "tax_price": "-0.01"
            },
            {
                "subtotal_price": "21.00"
            },
            {
                "subtotal_price": "21.00"
            },
            {
                "subtotal_price": "21.00"
            },
            {
                "subtotal_price": "21.00"
            },
            {
                "subtotal_price": "21.00"
            },
            {
                "subtotal_price": "21.00"
            },
            {
                "subtotal_price": "21.00"
            },
            {
                "subtotal_price": "2
generated_response {
    "menu": {
        "menu_id": "53300 kuala Lumpur",
        "menu_price": "53300.00047293",
        "menu_price_unit": "17.31"
    },
    "menu_price": {
        "menu_price_unit": "17.31"
    },
    "menu_price_unit": {
        "menu_price_unit": "17.31"
    },
    "menu_price_unit": {
        "menu_price_unit": "17.31"
    },
    "menu_price_unit": {
        "menu_price_unit": "17.31"
    },
    "menu_price_unit": {
        "menu_price_unit": "17.31"
    },
    "menu_price_unit": {
        "menu_price_unit": "17.31"
    },
    "menu_price_unit": {
        "menu_price_unit": "17.31"
    },
    "menu_price_unit": {
        "menu
generated_response {
    "menu": {
        "menu_id": "010000003512012070474201201000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
generated_response {
    "reprint": {
        "reprint_number": "43.36",
        "reprint_price": "43.36"
    },
    "total_payable": {
        "total_payable_price": "43.36",
        "total_payable_price_discount": "19.98"
    },
    "total_total_payable": {
        "total_payable_price": "23.38",
        "total_payable_discount": "7.44"
    }
}
generated_response {
    "id": "03119",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_price": "6.60",
    "total_
generated_response {
    "menu": {
        "nm": "SANYO STATIONERYN shop",
        "num": "316833G JALAN SETIA INDAH X,U13/X",
        "num": "SANYO STATIONERYN shop",
        "num": "40170 SETIA ALAM"
    },
    "menu": {
        "nm": "CASH SALES COUNTER RESTAURANT ORDER CHIT NCR",
        "num": "21020029",
        "num": "5.80 SR",
        "num": "5.80 SR",
        "num": "2 X 2.9000",
        "num": "5.80 SR",
        "num": "0.00"
    },
    "total": {
        "total_price": [
            {
                "nm": "CASH SALES COUNTER RESTAURANT ORDER CHIT NCR",
                "num": "21020029",
                "num": "5.80 SR",
                "num": "5.80 SR",
generated_response {
    "gst_summary": {
        "gst_summary_code": "74.20",
        "gst_summary_price": "70.00",
        "gst_summary_price_amount": "4.20"
    },
    "total_gst_summary": {
        "total_gst_summary_code": "70.00",
        "total_gst_summary_price": "70.00"
    },
    "total_gst_total_price": {
        "total_gst_price": "74.20"
    }
}
generated_response {
    "gst_summary": {
        "gst_summary_price": "6.00",
        "gst_price_price": "10.00%",
        "gst_price_price_price": "3.00"
    },
    "total_price": {
        "total_price_price": "53.00",
        "total_price_price_price": "53.00"
    },
    "total_price_price": {
        "total_price_price": "53.00"
    }
}
generated_response {
    "Invoice No": "1136284",
    "Invoice No": "02043319",
    "Invoice Date": "11-05-2018",
    "Invoice Type": "Tax Invoice",
    "Invoice Total": {
        "Qty": "2",
        "Qty": "U.P.",
        "Total": {
            "Qty": "1.70",
            "SR": "1",
            "Total": "0.20"
        }
    },
    "Description": {
        "Qty": "U.P.",
        "Qty": "1",
        "TOTAL": {
            "Qty": "1.79",
            "GST": "6%",
            "Amount": "1.90"
        }
    }
}
generated_response {
    "menu": [
        {
            "nm": "AEDON CO.",
            "num": "M",
            "brand": "AEDON MALI",
            "num": "FRL",
            "price": "12692-H"
        },
        {
            "nm": "3rd FR",
            "num": "AEDON MALI SC",
            "num": "JLJEKA",
            "price": "5150000017394688"
        },
        {
            "nm": "SUN-THU",
            "num": "1005 HRS",
            "price": "2200 HRS"
        },
        {
            "nm": "SHOPPING HOURS",
            "num": "5510000017394688"
        },
        {
            "nm": "FRI",
            "num": "1005 HRS",
            "price": "2200 HRS"
        },
        {
            "nm": "FRI-SAT",
            "num": "1005 HRS
generated_response {
    "menu": {
        "nm": "CS1801/26771",
        "cnt": "CS1801/26771",
        "price": "55.10",
        "price": "55.10"
    },
    "menuqty": {
        "nm": "QTY UP DISC",
        "price": "26.42"
    },
    "menuqtyqty": {
        "nm": "QTY UP DISC",
        "price": "24.00"
    },
    "menuqtyqtyqty": {
        "nm": "QTY DISC",
        "price": "24.00"
    }
}
generated_response {
    "Qty": "126926H",
    "Qty": "3rd FRCL AEON TAAM MALURI JNL JNJEJA",
    "Qty": "TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty": "3RD FRCL AEON TAAM MALURI",
    "Qty":
generated_response {
    "qty": [
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
generated_response {
    "entry_no": "00306020352",
    "entry_no_reg": "8806071-D",
    "entry_reg_no": "LOT 1851-A & 1851-B, JALAN KPB 6, KAWARSAN PERINDUSTRIBAL BALAKONG, SELANGOR BALANG, (GST ID No : 00306020352), IOI PUCHONG",
    "entry_reg_no": "501604",
    "entry_reg_no_reg": "8806071-D",
    "entry_reg_no_reg_no_reg": "SCOURPAD 5S 83",
    "entry_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_reg_no_
generated_response {
    "Recipient": {
        "Recipient_Name": "MAKASSAR FRESH MARKET SDN BHD",
        "Recipient_Address": [
            {
                "Recipient_Address_No": "40300 Shah Alam, Selangor",
                "Recipient_Address_Fax": "554232228",
                "Recipient_Fax_Date": "03-554232223"
            },
            {
                "Recipient_Address": "GST ID: 0030183900"
            },
            {
                "Recipient_Address": "JALAN SS 15/4B, JALAN SS 15/4B, JALAN SS 15/4B, JALAN SS 15/4B, JALAN SS 15/4B, JALAN SS 15/4B, JALAN SS 15/4B, JALAN SS 15/4B, JALAN SS 15/4B, JALAN SS 15/4
generated_response {'gst summary': ['Total Sales (Inclusive GST)', 'Change', '0'], ['GST Summary', ['Amount', 'RM', '67.55'], ['GST Summary', ['Amount', 'RM', '4.05'], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['GST Summary', ['Amount', 'RM', '67.55'], ['GST Summary', ['Amount', 'RM', '4.05'], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST', ''], ['Total Sales', ['Inclusive GST',
generated_response {
    "menu": {
        "menu_id": "M",
        "menu_price": "860671-D",
        "menu_price_tax_invoice": "S",
        "menu_price_tax_invoice_tax_price": "S"
    },
    "menu_price": {
        "menu_price_tax_invoice": "S"
    },
    "menu_price_tax_invoice": "S"
}
generated_response {
    "sub_shah_alam_seligor_d.e.
    "GST Reg: 001734164480
    "CASH RECEIPT
    "Total
    "Price
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "Total
    "
generated_response {
    "item": {
        "item_id": "99 SPEED MART S/B (519537-X)',
        "lot P.T. 2811', JALAN ANGSA.',
        "Taman BERKELEY",
        "41150 KLANG', SELANGOR
        "
    },
    "invoice_no": "18353/102/T0311",
    "GST_ID.NO": "000181747712",
    "total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total_sales_total
generated_response {
    "items": [
        {
            "id": "7",
            "items_id": "7",
            "total_saving": "0.00",
            "total_discounts": [
                {
                    "id": "18",
                    "price": "66.15"
                },
                {
                    "price": "-0.02"
                }
            },
            "total_discounts": [
                {
                    "price": "66.15"
                },
                {
                    "price": "-0.02"
                }
            ],
            "tax_amount": "0.00"
        },
        {
            "price": "5.90*4"
        }
    ],
    "total_discounts": [
        {
            "price": "66.15"
        },
        {
            "price": "-0.02"
        }
    ],
    "total_discounts": [
        {
            "price": "66.15"
        },
        {
            "price": "-0.02"
        }
    ],
    "total_discounts": [
        {
            "price": "66.1
✅ Terminé. F1: 0.00 | JSON Fail: 100.00% | CER: 3.00 | Precision: 0.00 | Recall: 0.00
🏃 View run Base_Model_Test at: https://dagshub.com/AhmadouBG/smolvlm-receipts.mlflow/#/experiments/0/runs/05a760a78fce4739a5e90a64d6dfe8b4
🧪 View experiment at: https://dagshub.com/AhmadouBG/smolvlm-receipts.mlflow/#/experiments/0

Configuration of image in the processor

In [ ]:
# Permet au modèle de voir plus de détails sur les tickets longs
processor.image_processor.do_resize = True
processor.image_processor.size = {"longest_edge": 768} # Teste 768 pour ton GPU Kaggle

Split data

In [ ]:
split_dataset = dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = split_dataset["train"]
test_dataset = split_dataset["test"]

Log of hugging face

In [ ]:
from google.colab import userdata
from huggingface_hub import login

token = userdata.get('checkpoint')
login(token=token)
# Colab vous demandera votre jeton (token) "Write"

### Supervised Fine-tuning (SFT)

In [ ]:
from trl import SFTConfig, SFTTrainer

args = SFTConfig(
    num_train_epochs=6,

    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,

    learning_rate=5e-5,
    weight_decay=0.01,

    logging_steps=10,
    eval_strategy="steps",
    eval_steps=100,
    save_steps=100,

    optim="adamw_torch",

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    seed=3407,


    remove_unused_columns=False,
    dataset_text_field="",
    dataset_kwargs={"skip_prepare_dataset": True},
    max_length=2048,

    report_to="none",
    output_dir="./SmolVLM-256M-Instruct-FineTuned-Receipt",

     # --- AJOUTS POUR HUGGING FACE ---
    push_to_hub=True,               # Active l'envoi automatique
    hub_model_id="gueye07/SmolVLM-Receipt-FineTune-No-Unslothv1", # Nom sur le Hub
    hub_strategy="checkpoint",
)

In [ ]:
trainer = SFTTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=collate_fn,
    peft_config=peft_config
)

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

In [ ]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: The AccumulateGrad node's stream does not match the stream of the node that produced the incoming gradient. This may incur unnecessary synchronization and break CUDA graph capture if the AccumulateGrad node's stream is the default stream. This mismatch is caused by an AccumulateGrad node created prior to the current iteration being kept alive. This can happen if the autograd graph is still being kept alive by tensors such as the loss, or if you are using DDP, which will stash a reference to the node. To resolve the mismatch, delete all references to the autograd graph or ensure that DDP initialization is performed under the same stream as subsequent forwards. If the mismatch is intentional, you can use torch.autograd.graph.set_warn_on_accumulate_grad_stream_mismatch(False) to suppress this warning. (Triggered internally at /pytorch/torch/csrc/autograd/input_buffer.cpp:240.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

### Recover the training checkpoint after the lost of session.

In [ ]:
from huggingface_hub import HfApi, RepoFile, RepoFolder

hf_api = HfApi()
repo_id = "gueye07/SmolVLM-Receipt-FineTune-No-Unslothv1"

print(f"Listing contents of Hugging Face repository: {repo_id}")

try:
    repo_files = hf_api.list_repo_tree(repo_id=repo_id, recursive=True)

    checkpoint_found = False
    for item in repo_files:
        # Only consider RepoFolder items for directories
        if isinstance(item, RepoFolder):
            if 'checkpoint' in item.path:
                print(f"Found checkpoint directory: {item.path} (RepoFolder)")
                checkpoint_found = True

    if not checkpoint_found:
        print("No checkpoint directories found in the repository.")
    else:
        print("Checkpoints successfully found in the repository.")

except Exception as e:
    print(f"Error accessing Hugging Face repository {repo_id}: {e}")
    print("Please ensure your Hugging Face token has write access and is correctly logged in (cell `v2yutATEMgxl`).")

Listing contents of Hugging Face repository: gueye07/SmolVLM-Receipt-FineTune-No-Unslothv1
Found checkpoint directory: last-checkpoint (RepoFolder)
Checkpoints successfully found in the repository.

In [ ]:
from huggingface_hub import snapshot_download
import os

# Define the Hugging Face repo ID where the checkpoints are stored
hf_checkpoint_repo_id = "gueye07/SmolVLM-Receipt-FineTune-No-Unslothv1"

# Define the local directory where the trainer expects to find the checkpoints
local_checkpoint_dir = "./SmolVLM-256M-Instruct-FineTuned-Receipt"

# Create the directory if it doesn't exist
os.makedirs(local_checkpoint_dir, exist_ok=True)

print(f"Downloading checkpoint from {hf_checkpoint_repo_id} to {local_checkpoint_dir}...")

# Download the entire repository contents to the local_checkpoint_dir
# This will include the 'last-checkpoint' folder if it exists in the repo
snapshot_download(repo_id=hf_checkpoint_repo_id, local_dir=local_checkpoint_dir)

print("✅ Checkpoint download complete!")

Downloading checkpoint from gueye07/SmolVLM-Receipt-FineTune-No-Unslothv1 to ./SmolVLM-256M-Instruct-FineTuned-Receipt...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 21 files:   0%|          | 0/21 [00:00<?, ?it/s]

✅ Checkpoint download complete!

In [ ]:
trainer.train(resume_from_checkpoint="./SmolVLM-256M-Instruct-FineTuned-Receipt/last-checkpoint")

/usr/local/lib/python3.12/dist-packages/torch/autograd/graph.py:865: UserWarning: The AccumulateGrad node's stream does not match the stream of the node that produced the incoming gradient. This may incur unnecessary synchronization and break CUDA graph capture if the AccumulateGrad node's stream is the default stream. This mismatch is caused by an AccumulateGrad node created prior to the current iteration being kept alive. This can happen if the autograd graph is still being kept alive by tensors such as the loss, or if you are using DDP, which will stash a reference to the node. To resolve the mismatch, delete all references to the autograd graph or ensure that DDP initialization is performed under the same stream as subsequent forwards. If the mismatch is intentional, you can use torch.autograd.graph.set_warn_on_accumulate_grad_stream_mismatch(False) to suppress this warning. (Triggered internally at /pytorch/torch/csrc/autograd/input_buffer.cpp:240.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

TrainOutput(global_step=642, training_loss=0.02600235601080541, metrics={'train_runtime': 2569.1479, 'train_samples_per_second': 1.997, 'train_steps_per_second': 0.25, 'total_flos': 3047012379227520.0, 'train_loss': 0.02600235601080541})

In [ ]:
merged_model = peft_model.merge_and_unload()
merged_model.save_pretrained("./merged-model-full")

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/bnb.py:397: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## Load and merged the fine-tuned model

In [ ]:
import torch
from transformers import AutoModelForImageTextToText, AutoProcessor
from peft import PeftModel
import gc

# Clear GPU memory
gc.collect()
torch.cuda.empty_cache()

# Define model IDs and paths
original_base_model_id = "HuggingFaceTB/SmolVLM-256M-Instruct"
peft_adapters_repo_id = "gueye07/SmolVLM-Receipt-FineTune-No-Unslothv1"
merged_fp16_local_path = "./smolvlm_merged_fp16_for_gguf"

print("\n--- Creating full-precision merged model for GGUF conversion ---")

# 1. Load the original base model in full float16 precision (NO quantization)
print(f"Loading base model {original_base_model_id} in float16...")
base_model_fp16 = AutoModelForImageTextToText.from_pretrained(
    original_base_model_id,
    device_map="cuda", # Load to CPU to save GPU memory for merging
    torch_dtype=torch.float16, # Ensure full precision
    _attn_implementation="sdpa"
)

# 2. Load the processor (it's the same for base and PEFT models)
processor_fp16 = AutoProcessor.from_pretrained(original_base_model_id)

# 3. Load the PEFT adapters onto the full-precision base model
print(f"Loading PEFT adapters from {peft_adapters_repo_id}...")
peft_model_fp16 = PeftModel.from_pretrained(base_model_fp16, peft_adapters_repo_id)

# 4. Merge the adapters into the base model
print("Merging PEFT adapters into the base model (full precision)...")
merged_model_fp16 = peft_model_fp16.merge_and_unload()

# 5. Save the full-precision merged model and processor locally
print(f"Saving full-precision merged model to {merged_fp16_local_path}...")
merged_model_fp16.save_pretrained(merged_fp16_local_path)
processor_fp16.save_pretrained(merged_fp16_local_path)

print("✅ Full-precision merged model saved locally for GGUF conversion!")

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

--- Creating full-precision merged model for GGUF conversion ---
Loading base model HuggingFaceTB/SmolVLM-256M-Instruct in float16...

Loading weights:   0%|          | 0/471 [00:00<?, ?it/s]

Loading PEFT adapters from gueye07/SmolVLM-Receipt-FineTune-No-Unslothv1...

adapter_config.json: 0.00B [00:00, ?B/s]

adapter_model.safetensors:   0%|          | 0.00/11.0M [00:00<?, ?B/s]

Merging PEFT adapters into the base model (full precision)...
Saving full-precision merged model to ./smolvlm_merged_fp16_for_gguf...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Full-precision merged model saved locally for GGUF conversion!

### Test with unseen data

In [ ]:
image_folder = "/kaggle/input/datasets/ahmadoubg/dataset-unseen/image_unseen/"
json_folder = "/kaggle/input/datasets/ahmadoubg/dataset-unseen/dto/"
output_path = "dataset_test.jsonl"

In [ ]:

from datasets import load_dataset
data_test = build_dataset(image_folder, json_folder, output_path)
dataset_test = load_dataset("json", data_files = data_test)['test']
len(dataset_test)

✅ Dataset ready (jsonl)

Generating test split: 0 examples [00:00, ? examples/s]

17

In [ ]:
dataset_test['test'][0]

{'img_path': '/kaggle/input/datasets/ahmadoubg/dataset-unseen/image_unseen/950.jpg',
 'messages': [{'role': 'user',
   'content': [{'type': 'image',
     'image': '/kaggle/input/datasets/ahmadoubg/dataset-unseen/image_unseen/950.jpg'},
    {'type': 'text',
     'text': 'Extract company, date, address and total from this receipt.\nIf missing return null.\nDo NOT guess.\nReturn ONLY valid JSON.'}]},
  {'role': 'assistant',
   'content': [{'type': 'text',
     'text': '{"company": "KEDAI PAPAN YEW CHUAN", "date": "11/05/2018", "address": "LOT 276 JALAN BANTING 43800 DENGKIL, SELANGOR", "total": "68.90"}'}]}]}

In [ ]:
dataset_test_processed = dataset_test.map(
    process_metadata,
    remove_columns=dataset_test.column_names # Replace original columns with new ones from process_metadata
)

run_and_log_evaluation(merged_model_fp16, dataset_test_processed, run_name="FineTuned_Model_Test")

Map:   0%|          | 0/17 [00:00<?, ? examples/s]

generated_response {
    "company": "KEDAI PAPAN YEW CHUAN",
    "date": "11/05/2018",
    "address": "LOT 276 JALAN BANTING",
    "total": "68.90"
}
generated_response {
    "company": "M.A.S.H. DISTRIBUTOR & MARKETING SDN BHD",
    "date": "20/06/2018",
    "address": "10400 PENANG",
    "total": "85.20"
}
generated_response {
    "clg": "GL HANDICRAFT & TAILORING",
    "gst": "1000194632736",
    "company": "MALAYSIA",
    "orderprice": "R 100.00",
    "totalprice": "R 100.00"
}
generated_response {
    "company": "ONE THREE SEAFOOD RESTAURANT SDN BHD",
    "date": "20-06-2018",
    "address": "43800 DENGKIL, JALAN AIR HITAM",
    "total": "38.00"
}
generated_response { "company": "OCEAN L.C. PACKAGING ENTERPRISE", "date": "27/06/2018", "address": "OCEAN L.C. PACKAGING ENTERPRISE", "total": "12.45"}
generated_response {
    "company": "PASAR RAYO MEGA MAJU",
    "date": "NO 24, 25 & 26, JALAN PASAT PERNIAGAAN BUNGA RAYA 4, PASAT PERNIAGAAN BUNGA RAYA, TEL: 01-283886",
    "price": "01-283886",
    "cashprice": "0.00"
},

{
    "cashprice": "0.00"
}

// SALES, COSIT AND REPAIR
{
    "cashprice": "30.45",
    "totalprice": "30.45"
}

{
    "cashprice": "0.00"
}

{
    "cashprice": "0.00"
}

{
    "cashprice": "30.45"
}

{
    "cashprice": "0.00"
}

{
    "cashprice": "0.00"
}

{
    "
generated_response {
    "company": "MR. D.I.Y. (M) SDN BHD",
    "date": "15-07-18",
    "address": "LOT 1851, CO. REG, 860671-D",
    "total": "13.05"
}
generated_response {
    "company": "ONE THREE SEAFOOD RESTAURANT SDN BHD",
    "date": "14-06-2018",
    "address": "113 CASHIER",
    "total": "59.00"
}
generated_response {
    "company": "LIAN HING STATIONERY SDN BHD",
    "date": "27.03.2018",
    "address": "NO. 32, 33, JALAN SR 1/9, SEKASYEN 9, 43300 SERI KEMBANGAN, SELANGOR",
    "total": "12.00"
}
generated_response {
    "company": "ONE THREE SEAFOOD RESTAURANT SDN BHD",
    "date": "11-06-2018",
    "address": "43800 DENGKIL, JALAN AIR HITAM",
    "total": "58.00"
}
✅ Terminé. F1: 0.61 | JSON Fail: 0.00% | CER: 0.55 | Precision: 0.50 | Recall: 0.80
🏃 View run FineTuned_Model_Test at: https://dagshub.com/AhmadouBG/smolvlm-receipts.mlflow/#/experiments/0/runs/51a8fdbb23024b93964b7a6310740275
🧪 View experiment at: https://dagshub.com/AhmadouBG/smolvlm-receipts.mlflow/#/experiments/0

## Convert the Merged Model to GGUF Format

Now that the fully merged model (base + LoRA adapters) is on the Hugging Face Hub, we can use the `llama.cpp` conversion script to convert it into the GGUF format. We'll generate two versions: F16 (full precision) and Q8_0 (8-bit quantized) for optimal performance and size balance.

## Install llama.cpp for convertion in gguf model

In [ ]:
!apt-get update
!apt-get install pciutils build-essential cmake curl libcurl4-openssl-dev -y
!git clone https://github.com/ggml-org/llama.cpp

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:5 https://cli.github.com/packages stable InRelease [3,917 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,915 kB]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,294 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,004 kB]
Get:13 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [91.2 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [61.6 kB]
Hit:15 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:16 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,614 kB]
Hit:17 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:18 https://cli.github.com/packages stable/main amd64 Packages [356 B]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,247 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [86.0 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,602 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,251 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.8 kB]
Get:25 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.2 MB]
Get:26 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.9 kB]
Get:27 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,001 kB]
Fetched 41.9 MB in 3s (15.4 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).
The following additional packages will be installed:
  libcurl4 libpci3 pci.ids
Suggested packages:
  libcurl4-doc libidn11-dev libldap2-dev librtmp-dev
The following NEW packages will be installed:
  libpci3 pci.ids pciutils
The following packages will be upgraded:
  curl libcurl4 libcurl4-openssl-dev
3 upgraded, 3 newly installed, 0 to remove and 215 not upgraded.
Need to get 1,215 kB of archives.
After this operation, 1,586 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 pci.ids all 0.0~2022.01.22-1ubuntu0.1 [251 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpci3 amd64 1:3.7.0-6 [28.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 pciutils amd64 1:3.7.0-6 [63.6 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4-openssl-dev amd64 7.81.0-1ubuntu1.24 [387 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 curl amd64 7.81.0-1ubuntu1.24 [194 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4 amd64 7.81.0-1ubuntu1.24 [291 kB]
Fetched 1,215 kB in 0s (16.8 MB/s)
Selecting previously unselected package pci.ids.
(Reading database ... 124626 files and directories currently installed.)
Preparing to unpack .../0-pci.ids_0.0~2022.01.22-1ubuntu0.1_all.deb ...
Unpacking pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Selecting previously unselected package libpci3:amd64.
Preparing to unpack .../1-libpci3_1%3a3.7.0-6_amd64.deb ...
Unpacking libpci3:amd64 (1:3.7.0-6) ...
Selecting previously unselected package pciutils.
Preparing to unpack .../2-pciutils_1%3a3.7.0-6_amd64.deb ...
Unpacking pciutils (1:3.7.0-6) ...
Preparing to unpack .../3-libcurl4-openssl-dev_7.81.0-1ubuntu1.24_amd64.deb ...
Unpacking libcurl4-openssl-dev:amd64 (7.81.0-1ubuntu1.24) over (7.81.0-1ubuntu1.21) ...
Preparing to unpack .../4-curl_7.81.0-1ubuntu1.24_amd64.deb ...
Unpacking curl (7.81.0-1ubuntu1.24) over (7.81.0-1ubuntu1.21) ...
Preparing to unpack .../5-libcurl4_7.81.0-1ubuntu1.24_amd64.deb ...
Unpacking libcurl4:amd64 (7.81.0-1ubuntu1.24) over (7.81.0-1ubuntu1.21) ...
Setting up pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Setting up libpci3:amd64 (1:3.7.0-6) ...
Setting up libcurl4:amd64 (7.81.0-1ubuntu1.24) ...
Setting up curl (7.81.0-1ubuntu1.24) ...
Setting up libcurl4-openssl-dev:amd64 (7.81.0-1ubuntu1.24) ...
Setting up pciutils (1:3.7.0-6) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Cloning into 'llama.cpp'...
remote: Enumerating objects: 92640, done.
remote: Counting objects: 100% (380/380), done.
remote: Compressing objects: 100% (223/223), done.
remote: Total 92640 (delta 268), reused 158 (delta 157), pack-reused 92260 (from 3)
Receiving objects: 100% (92640/92640), 386.49 MiB | 40.86 MiB/s, done.
Resolving deltas: 100% (65682/65682), done.

In [ ]:
%cd llama.cpp
!cmake -B build -DBUILD_SHARED_LIBS=OFF -DGGML_CUDA=OFF # Changed DGGML_CUDA=ON to OFF to avoid CUDA linking error
!cmake --build build --config Release -j 12 --clean-first --target llama-quantize llama-cli llama-mtmd-cli llama-server llama-gguf-split
!cp build/bin/llama-* .
!ls -l .

/kaggle/working/llama.cpp
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.34.1")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- ggml version: 0.11.0
-- ggml commit:  f9cd456ea
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.2")
-- Performing Test OPENSSL_VERSION_SUPPORTED
-- Performing Test OPENSSL_VERSION_SUPPORTED - Success
-- OpenSSL found: 3.0.2
-- Generating embedded license file for target: llama-common
-- Configuring done (1.8s)
-- Generating done (0.4s)
-- Build files have been written to: /kaggle/working/llama.cpp/build
[  0%] Building CXX object vendor/cpp-httplib/CMakeFiles/cpp-httplib.dir/httplib.cpp.o
[  0%] Building CXX object common/CMakeFiles/llama-common-base.dir/build-info.cpp.o
[  0%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml.cpp.o
[  0%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  2%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend-meta.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  4%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  4%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
[  4%] Linking CXX static library libllama-common-base.a
[  4%] Built target llama-common-base
[  4%] Linking CXX static library libggml-base.a
[  4%] Built target ggml-base
[  4%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.c.o
[  4%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/repack.cpp.o
[  6%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/quants.c.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/hbm.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/traits.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/amx.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/mmq.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/binary-ops.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/unary-ops.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/vec.cpp.o
[  9%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ops.cpp.o
[ 11%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/llamafile/sgemm.cpp.o
[ 11%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/quants.c.o
[ 11%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/repack.cpp.o
[ 11%] Linking CXX static library libggml-cpu.a
[ 11%] Built target ggml-cpu
[ 13%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-dl.cpp.o
[ 13%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-reg.cpp.o
[ 13%] Linking CXX static library libggml.a
[ 13%] Built target ggml
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-adapter.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-arch.cpp.o
[ 13%] Building CXX object src/CMakeFiles/llama.dir/llama-batch.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-chat.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-context.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-cparams.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-graph.cpp.o
[ 15%] Building CXX object src/CMakeFiles/llama.dir/llama-grammar.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-hparams.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-impl.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-io.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache.cpp.o
[ 18%] Building CXX object src/CMakeFiles/llama.dir/llama-kv-cache-iswa.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-memory.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-hybrid.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-hybrid-iswa.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-memory-recurrent.cpp.o
[ 20%] Building CXX object src/CMakeFiles/llama.dir/llama-mmap.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/llama-model-loader.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/llama-model-saver.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/llama-model.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/llama-quant.cpp.o
[ 22%] Building CXX object src/CMakeFiles/llama.dir/llama-sampler.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/llama-vocab.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/unicode-data.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/unicode.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/afmoe.cpp.o
[ 25%] Building CXX object src/CMakeFiles/llama.dir/models/apertus.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/arcee.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/arctic.cpp.o
[ 27%] Linking CXX static library libcpp-httplib.a
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/arwkv7.cpp.o
[ 27%] Built target cpp-httplib
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/baichuan.cpp.o
[ 27%] Building CXX object src/CMakeFiles/llama.dir/models/bailingmoe.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/bailingmoe2.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/bert.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/bitnet.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/bloom.cpp.o
[ 29%] Building CXX object src/CMakeFiles/llama.dir/models/chameleon.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/chatglm.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/codeshell.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/cogvlm.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/cohere2.cpp.o
[ 31%] Building CXX object src/CMakeFiles/llama.dir/models/command-r.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/dbrx.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/deci.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek.cpp.o
[ 34%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek2.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/deepseek2ocr.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/delta-net-base.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/dots1.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/dream.cpp.o
[ 36%] Building CXX object src/CMakeFiles/llama.dir/models/ernie4-5-moe.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/ernie4-5.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/eurobert.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/exaone-moe.cpp.o
[ 38%] Building CXX object src/CMakeFiles/llama.dir/models/exaone.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/falcon-h1.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/exaone4.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/falcon.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/gemma-embedding.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/gemma.cpp.o
[ 40%] Building CXX object src/CMakeFiles/llama.dir/models/gemma2.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/gemma3.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/gemma3n.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/gemma4.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/glm-dsa.cpp.o
[ 43%] Building CXX object src/CMakeFiles/llama.dir/models/glm4-moe.cpp.o
[ 45%] Building CXX object src/CMakeFiles/llama.dir/models/glm4.cpp.o
[ 45%] Building CXX object src/CMakeFiles/llama.dir/models/gpt2.cpp.o
[ 45%] Building CXX object src/CMakeFiles/llama.dir/models/gptneox.cpp.o
[ 45%] Building CXX object src/CMakeFiles/llama.dir/models/granite-hybrid.cpp.o
[ 45%] Building CXX object src/CMakeFiles/llama.dir/models/granite-moe.cpp.o
[ 47%] Building CXX object src/CMakeFiles/llama.dir/models/granite.cpp.o
[ 47%] Building CXX object src/CMakeFiles/llama.dir/models/grok.cpp.o
[ 47%] Building CXX object src/CMakeFiles/llama.dir/models/grovemoe.cpp.o
[ 47%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-dense.cpp.o
[ 47%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-moe.cpp.o
[ 50%] Building CXX object src/CMakeFiles/llama.dir/models/hunyuan-vl.cpp.o
[ 50%] Building CXX object src/CMakeFiles/llama.dir/models/internlm2.cpp.o
[ 50%] Building CXX object src/CMakeFiles/llama.dir/models/jais.cpp.o
[ 50%] Building CXX object src/CMakeFiles/llama.dir/models/jais2.cpp.o
[ 50%] Building CXX object src/CMakeFiles/llama.dir/models/jamba.cpp.o
[ 52%] Building CXX object src/CMakeFiles/llama.dir/models/jina-bert-v2.cpp.o
[ 52%] Building CXX object src/CMakeFiles/llama.dir/models/jina-bert-v3.cpp.o
[ 52%] Building CXX object src/CMakeFiles/llama.dir/models/kimi-linear.cpp.o
[ 52%] Building CXX object src/CMakeFiles/llama.dir/models/lfm2.cpp.o
[ 52%] Building CXX object src/CMakeFiles/llama.dir/models/lfm2moe.cpp.o
[ 54%] Building CXX object src/CMakeFiles/llama.dir/models/llada-moe.cpp.o
[ 54%] Building CXX object src/CMakeFiles/llama.dir/models/llada.cpp.o
[ 54%] Building CXX object src/CMakeFiles/llama.dir/models/llama-embed.cpp.o
[ 54%] Building CXX object src/CMakeFiles/llama.dir/models/llama.cpp.o
[ 54%] Building CXX object src/CMakeFiles/llama.dir/models/llama4.cpp.o
[ 56%] Building CXX object src/CMakeFiles/llama.dir/models/maincoder.cpp.o
[ 56%] Building CXX object src/CMakeFiles/llama.dir/models/mamba-base.cpp.o
[ 56%] Building CXX object src/CMakeFiles/llama.dir/models/mamba.cpp.o
[ 56%] Building CXX object src/CMakeFiles/llama.dir/models/mamba2.cpp.o
[ 56%] Building CXX object src/CMakeFiles/llama.dir/models/mimo2.cpp.o
[ 59%] Building CXX object src/CMakeFiles/llama.dir/models/minicpm.cpp.o
[ 59%] Building CXX object src/CMakeFiles/llama.dir/models/minicpm3.cpp.o
[ 59%] Building CXX object src/CMakeFiles/llama.dir/models/minimax-m2.cpp.o
[ 59%] Building CXX object src/CMakeFiles/llama.dir/models/mistral3.cpp.o
[ 59%] Building CXX object src/CMakeFiles/llama.dir/models/mistral4.cpp.o
[ 61%] Building CXX object src/CMakeFiles/llama.dir/models/modern-bert.cpp.o
[ 61%] Building CXX object src/CMakeFiles/llama.dir/models/mpt.cpp.o
[ 61%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron-h-moe.cpp.o
[ 61%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron-h.cpp.o
[ 61%] Building CXX object src/CMakeFiles/llama.dir/models/nemotron.cpp.o
[ 63%] Building CXX object src/CMakeFiles/llama.dir/models/neo-bert.cpp.o
[ 63%] Building CXX object src/CMakeFiles/llama.dir/models/nomic-bert-moe.cpp.o
[ 63%] Building CXX object src/CMakeFiles/llama.dir/models/nomic-bert.cpp.o
[ 63%] Building CXX object src/CMakeFiles/llama.dir/models/olmo.cpp.o
[ 63%] Building CXX object src/CMakeFiles/llama.dir/models/olmo2.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/olmoe.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/openai-moe.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/openelm.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/orion.cpp.o
[ 65%] Building CXX object src/CMakeFiles/llama.dir/models/paddleocr.cpp.o
[ 68%] Building CXX object src/CMakeFiles/llama.dir/models/pangu-embed.cpp.o
[ 68%] Building CXX object src/CMakeFiles/llama.dir/models/phi2.cpp.o
[ 68%] Building CXX object src/CMakeFiles/llama.dir/models/phi3.cpp.o
[ 68%] Building CXX object src/CMakeFiles/llama.dir/models/phimoe.cpp.o
[ 68%] Building CXX object src/CMakeFiles/llama.dir/models/plamo.cpp.o
[ 70%] Building CXX object src/CMakeFiles/llama.dir/models/plamo2.cpp.o
[ 70%] Building CXX object src/CMakeFiles/llama.dir/models/plamo3.cpp.o
[ 70%] Building CXX object src/CMakeFiles/llama.dir/models/plm.cpp.o
[ 70%] Building CXX object src/CMakeFiles/llama.dir/models/qwen.cpp.o
[ 70%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2moe.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen2vl.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3.cpp.o
[ 72%] Building CXX object src/CMakeFiles/llama.dir/models/qwen35.cpp.o
[ 75%] Building CXX object src/CMakeFiles/llama.dir/models/qwen35moe.cpp.o
[ 75%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3moe.cpp.o
[ 75%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3next.cpp.o
[ 75%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3vl.cpp.o
[ 75%] Building CXX object src/CMakeFiles/llama.dir/models/qwen3vlmoe.cpp.o
[ 77%] Building CXX object src/CMakeFiles/llama.dir/models/refact.cpp.o
[ 77%] Building CXX object src/CMakeFiles/llama.dir/models/rnd1.cpp.o
[ 77%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6-base.cpp.o
[ 77%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6.cpp.o
[ 77%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv6qwen2.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv7-base.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/rwkv7.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/seed-oss.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/smallthinker.cpp.o
[ 79%] Building CXX object src/CMakeFiles/llama.dir/models/smollm3.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/stablelm.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/starcoder.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/starcoder2.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/step35.cpp.o
[ 81%] Building CXX object src/CMakeFiles/llama.dir/models/t5.cpp.o
[ 84%] Building CXX object src/CMakeFiles/llama.dir/models/t5encoder.cpp.o
[ 84%] Building CXX object src/CMakeFiles/llama.dir/models/wavtokenizer-dec.cpp.o
[ 84%] Building CXX object src/CMakeFiles/llama.dir/models/xverse.cpp.o
[ 84%] Linking CXX static library libllama.a
[ 84%] Built target llama
[ 84%] Building CXX object common/CMakeFiles/llama-common.dir/arg.cpp.o
[ 84%] Building CXX object common/CMakeFiles/llama-common.dir/chat-auto-parser-generator.cpp.o
[ 84%] Building CXX object common/CMakeFiles/llama-common.dir/chat-auto-parser-helpers.cpp.o
[ 86%] Building CXX object common/CMakeFiles/llama-common.dir/chat-diff-analyzer.cpp.o
[ 86%] Building CXX object common/CMakeFiles/llama-common.dir/chat-peg-parser.cpp.o
[ 86%] Building CXX object common/CMakeFiles/llama-common.dir/chat.cpp.o
[ 86%] Building CXX object common/CMakeFiles/llama-common.dir/common.cpp.o
[ 86%] Building CXX object common/CMakeFiles/llama-common.dir/console.cpp.o
[ 86%] Building CXX object common/CMakeFiles/llama-common.dir/hf-cache.cpp.o
[ 86%] Building CXX object common/CMakeFiles/llama-common.dir/fit.cpp.o
[ 86%] Building CXX object common/CMakeFiles/llama-common.dir/download.cpp.o
[ 88%] Building CXX object common/CMakeFiles/llama-common.dir/debug.cpp.o
[ 88%] Building CXX object common/CMakeFiles/llama-common.dir/json-partial.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/json-schema-to-grammar.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/llguidance.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/log.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/ngram-cache.cpp.o
[ 90%] Building CXX object common/CMakeFiles/llama-common.dir/ngram-map.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/ngram-mod.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/peg-parser.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/preset.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/regex-partial.cpp.o
[ 93%] Building CXX object common/CMakeFiles/llama-common.dir/reasoning-budget.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/sampling.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/speculative.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/unicode.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/lexer.cpp.o
[ 95%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/parser.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/runtime.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/value.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/string.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/jinja/caps.cpp.o
[ 97%] Building CXX object common/CMakeFiles/llama-common.dir/__/license.cpp.o
[100%] Linking CXX static library libllama-common.a
[100%] Built target llama-common
[100%] Building CXX object tools/quantize/CMakeFiles/llama-quantize.dir/quantize.cpp.o
[100%] Linking CXX executable ../../bin/llama-quantize
[100%] Built target llama-quantize
[  0%] Built target llama-common-base
[  0%] Built target cpp-httplib
[  3%] Built target ggml-base
[  9%] Built target ggml-cpu
[ 11%] Built target ggml
[ 69%] Built target llama
[ 69%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd.cpp.o
[ 71%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd-image.cpp.o
[ 71%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd-helper.cpp.o
[ 71%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/mtmd-audio.cpp.o
[ 71%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/clip.cpp.o
[ 71%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/cogvlm.cpp.o
[ 71%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/gemma4a.cpp.o
[ 71%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/conformer.cpp.o
[ 73%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/dotsocr.cpp.o
[ 73%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/gemma4v.cpp.o
[ 73%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/glm4v.cpp.o
[ 86%] Built target llama-common
[ 86%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/granite-speech.cpp.o
[ 88%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/hunyuanocr.cpp.o
[ 88%] Building CXX object tools/mtmd/CMakeFiles/mtmd.dir/models/internvl.cpp.o

### Convert in gguf in f16

In [ ]:
%cd /kaggle/working/

# Define the local path for the full-precision merged model
merged_fp16_local_path = "./smolvlm_merged_fp16_for_gguf"

# Convert to F16 GGUF
print(f"Converting full-precision merged model to F16 GGUF from {merged_fp16_local_path}...")
!python llama.cpp/convert_hf_to_gguf.py "{merged_fp16_local_path}" \
    --outfile smolvlm_receipt_merged_f16.gguf --outtype f16
print("✅ F16 GGUF conversion complete!")

/kaggle/working
Converting full-precision merged model to F16 GGUF from ./smolvlm_merged_fp16_for_gguf...
INFO:hf-to-gguf:Loading model: smolvlm_merged_fp16_for_gguf
INFO:hf-to-gguf:Model architecture: VLlama3ForCausalLM
INFO:hf-to-gguf:gguf: indexing model part 'model.safetensors'
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:output.weight,               torch.float16 --> F16, shape = {576, 49280}
INFO:hf-to-gguf:token_embd.weight,           torch.float16 --> F16, shape = {576, 49280}
INFO:hf-to-gguf:blk.0.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.0.ffn_down.weight,       torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.0.ffn_gate.weight,       torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.0.ffn_up.weight,         torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.0.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.0.attn_k.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.0.attn_output.weight,    torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.0.attn_q.weight,         torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.0.attn_v.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.1.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.1.ffn_down.weight,       torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.1.ffn_gate.weight,       torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.1.ffn_up.weight,         torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.1.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.1.attn_k.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.1.attn_output.weight,    torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.1.attn_q.weight,         torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.1.attn_v.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.10.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.10.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.10.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.10.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.10.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.10.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.10.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.10.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.10.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.11.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.11.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.11.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.11.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.11.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.11.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.11.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.11.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.11.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.12.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.12.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.12.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.12.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.12.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.12.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.12.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.12.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.12.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.13.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.13.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.13.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.13.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.13.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.13.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.13.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.13.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.13.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.14.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.14.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.14.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.14.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.14.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.14.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.14.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.14.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.14.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.15.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.15.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.15.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.15.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.15.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.15.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.15.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.15.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.15.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.16.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.16.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.16.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.16.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.16.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.16.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.16.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.16.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.16.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.17.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.17.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.17.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.17.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.17.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.17.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.17.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.17.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.17.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.18.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.18.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.18.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.18.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.18.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.18.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.18.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.18.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.18.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.19.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.19.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.19.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.19.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.19.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.19.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.19.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.19.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.19.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.2.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.2.ffn_down.weight,       torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.2.ffn_gate.weight,       torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.2.ffn_up.weight,         torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.2.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.2.attn_k.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.2.attn_output.weight,    torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.2.attn_q.weight,         torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.2.attn_v.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.20.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.20.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.20.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.20.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.20.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.20.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.20.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.20.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.20.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.21.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.21.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.21.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.21.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.21.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.21.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.21.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.21.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.21.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.22.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.22.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.22.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.22.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.22.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.22.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.22.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.22.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.22.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.23.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.23.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.23.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.23.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.23.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.23.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.23.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.23.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.23.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.24.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.24.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.24.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.24.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.24.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.24.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.24.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.24.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.24.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.25.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.25.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.25.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.25.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.25.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.25.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.25.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.25.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.25.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.26.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.26.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.26.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.26.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.26.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.26.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.26.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.26.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.26.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.27.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.27.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.27.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.27.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.27.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.27.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.27.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.27.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.27.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.28.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.28.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.28.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.28.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.28.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.28.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.28.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.28.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.28.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.29.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.29.ffn_down.weight,      torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.29.ffn_gate.weight,      torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.29.ffn_up.weight,        torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.29.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.29.attn_k.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.29.attn_output.weight,   torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.29.attn_q.weight,        torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.29.attn_v.weight,        torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.3.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.3.ffn_down.weight,       torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.3.ffn_gate.weight,       torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.3.ffn_up.weight,         torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.3.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.3.attn_k.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.3.attn_output.weight,    torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.3.attn_q.weight,         torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.3.attn_v.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.4.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.4.ffn_down.weight,       torch.float16 --> F16, shape = {1536, 576}
INFO:hf-to-gguf:blk.4.ffn_gate.weight,       torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.4.ffn_up.weight,         torch.float16 --> F16, shape = {576, 1536}
INFO:hf-to-gguf:blk.4.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.4.attn_k.weight,         torch.float16 --> F16, shape = {576, 192}
INFO:hf-to-gguf:blk.4.attn_output.weight,    torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.4.attn_q.weight,         torch.float16 --> F16, shape = {576, 576}
INFO:hf-to-gguf:blk.4.attn_v.weight,         torch.float16 --> F16, shape = {576, 192}

In [ ]:
%cd /kaggle/working/

# Define the Hugging Face repo ID for the merged model
merged_hf_repo_id = "gueye07/SmolVLM-256M-Instruct-FineTuned-Merged"

# Convert to F16 GGUF
print(f"Converting {merged_hf_repo_id} to F16 GGUF...")
!python llama.cpp/convert_hf_to_gguf.py "{merged_hf_repo_id}" \
    --outfile smolvlm_receipt_merged_f16.gguf --outtype f16
print("✅ F16 GGUF conversion complete!")

#### Convert in gguf in f16 immproj model

In [ ]:
%cd /kaggle/working/

# Define the local path for the full-precision merged model
merged_fp16_local_path = "./smolvlm_merged_fp16_for_gguf"

# Convert to F16 GGUF with mmproj
print(f"Converting full-precision merged model to F16 GGUF with mmproj from {merged_fp16_local_path}...")
!python llama.cpp/convert_hf_to_gguf.py "{merged_fp16_local_path}" \
    --outfile mmproj_smolvlm_receipt_merged_f16.gguf --outtype f16 --mmproj
print("✅ F16 mmproj GGUF conversion complete!")

/kaggle/working
Converting full-precision merged model to F16 GGUF with mmproj from ./smolvlm_merged_fp16_for_gguf...
INFO:hf-to-gguf:Loading model: smolvlm_merged_fp16_for_gguf
INFO:hf-to-gguf:Model architecture: Idefics3ForConditionalGeneration
INFO:hf-to-gguf:gguf: indexing model part 'model.safetensors'
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:mm.model.fc.weight,                   torch.float16 --> F16, shape = {12288, 576}
INFO:hf-to-gguf:v.patch_embd.bias,                    torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.patch_embd.weight,                  torch.float16 --> F32, shape = {16, 16, 3, 768}
INFO:hf-to-gguf:v.position_embd.weight,               torch.float16 --> F32, shape = {768, 1024}
INFO:hf-to-gguf:v.blk.0.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.0.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.0.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.0.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.0.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.0.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.0.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.0.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.1.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.1.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.1.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.1.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.1.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.1.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.1.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.1.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.10.ln1.bias,                    torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.ln1.weight,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.ln2.bias,                    torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.ln2.weight,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.ffn_up.bias,                 torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.10.ffn_up.weight,               torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.10.ffn_down.bias,               torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.ffn_down.weight,             torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.10.attn_k.bias,                 torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.attn_k.weight,               torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.10.attn_out.bias,               torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.attn_out.weight,             torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.10.attn_q.bias,                 torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.attn_q.weight,               torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.10.attn_v.bias,                 torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.10.attn_v.weight,               torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.11.ln1.bias,                    torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.ln1.weight,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.ln2.bias,                    torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.ln2.weight,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.ffn_up.bias,                 torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.11.ffn_up.weight,               torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.11.ffn_down.bias,               torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.ffn_down.weight,             torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.11.attn_k.bias,                 torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.attn_k.weight,               torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.11.attn_out.bias,               torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.attn_out.weight,             torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.11.attn_q.bias,                 torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.attn_q.weight,               torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.11.attn_v.bias,                 torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.11.attn_v.weight,               torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.2.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.2.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.2.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.2.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.2.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.2.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.2.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.2.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.3.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.3.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.3.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.3.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.3.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.3.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.3.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.3.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.4.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.4.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.4.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.4.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.4.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.4.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.4.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.4.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.5.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.5.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.5.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.5.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.5.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.5.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.5.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.5.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.6.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.6.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.6.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.6.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.6.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.6.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.6.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.6.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.7.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.7.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.7.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.7.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.7.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.7.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.7.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.7.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.8.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.8.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.8.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.8.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.8.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.8.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.8.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.8.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.9.ln1.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.ln1.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.ln2.bias,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.ln2.weight,                   torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.ffn_up.bias,                  torch.float16 --> F32, shape = {3072}
INFO:hf-to-gguf:v.blk.9.ffn_up.weight,                torch.float16 --> F16, shape = {768, 3072}
INFO:hf-to-gguf:v.blk.9.ffn_down.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.ffn_down.weight,              torch.float16 --> F16, shape = {3072, 768}
INFO:hf-to-gguf:v.blk.9.attn_k.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.attn_k.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.9.attn_out.bias,                torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.attn_out.weight,              torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.9.attn_q.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.attn_q.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.blk.9.attn_v.bias,                  torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.blk.9.attn_v.weight,                torch.float16 --> F16, shape = {768, 768}
INFO:hf-to-gguf:v.post_ln.bias,                       torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:v.post_ln.weight,                     torch.float16 --> F32, shape = {768}
INFO:hf-to-gguf:Set meta model
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:Set model quantization version
INFO:gguf.gguf_writer:Writing the following files:
INFO:gguf.gguf_writer:mmproj_smolvlm_receipt_merged_f16.gguf: n_tensors = 198, total_size = 190.0M
Writing: 100%|████████████████████████████| 190M/190M [00:00<00:00, 1.02Gbyte/s]
INFO:hf-to-gguf:Model successfully exported to mmproj_smolvlm_receipt_merged_f16.gguf
✅ F16 mmproj GGUF conversion complete!

In [ ]:
%cd /kaggle/working/

# Define the local path for the full-precision merged model
merged_fp16_local_path = "./smolvlm_merged_fp16_for_gguf"

# Convert to Q8_0 GGUF (8-bit quantization)
print(f"Converting full-precision merged model to Q8_0 GGUF from {merged_fp16_local_path}...")
!python llama.cpp/convert_hf_to_gguf.py "{merged_fp16_local_path}" \
    --outfile smolvlm_receipt_merged_q8_0.gguf --outtype q8_0
print("✅ Q8_0 GGUF conversion complete!")

/kaggle/working
Converting full-precision merged model to Q8_0 GGUF from ./smolvlm_merged_fp16_for_gguf...
INFO:hf-to-gguf:Loading model: smolvlm_merged_fp16_for_gguf
INFO:numexpr.utils:NumExpr defaulting to 4 threads.
INFO:hf-to-gguf:Model architecture: VLlama3ForCausalLM
INFO:hf-to-gguf:gguf: indexing model part 'model.safetensors'
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Exporting model...
INFO:hf-to-gguf:output.weight,               torch.float16 --> Q8_0, shape = {576, 49280}
INFO:hf-to-gguf:token_embd.weight,           torch.float16 --> Q8_0, shape = {576, 49280}
INFO:hf-to-gguf:blk.0.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.0.ffn_down.weight,       torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.0.ffn_gate.weight,       torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.0.ffn_up.weight,         torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.0.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.0.attn_k.weight,         torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.0.attn_output.weight,    torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.0.attn_q.weight,         torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.0.attn_v.weight,         torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.1.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.1.ffn_down.weight,       torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.1.ffn_gate.weight,       torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.1.ffn_up.weight,         torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.1.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.1.attn_k.weight,         torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.1.attn_output.weight,    torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.1.attn_q.weight,         torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.1.attn_v.weight,         torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.10.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.10.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.10.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.10.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.10.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.10.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.10.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.10.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.10.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.11.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.11.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.11.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.11.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.11.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.11.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.11.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.11.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.11.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.12.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.12.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.12.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.12.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.12.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.12.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.12.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.12.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.12.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.13.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.13.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.13.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.13.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.13.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.13.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.13.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.13.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.13.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.14.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.14.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.14.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.14.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.14.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.14.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.14.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.14.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.14.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.15.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.15.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.15.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.15.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.15.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.15.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.15.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.15.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.15.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.16.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.16.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.16.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.16.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.16.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.16.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.16.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.16.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.16.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.17.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.17.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.17.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.17.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.17.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.17.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.17.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.17.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.17.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.18.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.18.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.18.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.18.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.18.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.18.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.18.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.18.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.18.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.19.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.19.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.19.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.19.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.19.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.19.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.19.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.19.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.19.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.2.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.2.ffn_down.weight,       torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.2.ffn_gate.weight,       torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.2.ffn_up.weight,         torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.2.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.2.attn_k.weight,         torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.2.attn_output.weight,    torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.2.attn_q.weight,         torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.2.attn_v.weight,         torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.20.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.20.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.20.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.20.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.20.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.20.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.20.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.20.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.20.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.21.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.21.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.21.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.21.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.21.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.21.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.21.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.21.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.21.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.22.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.22.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.22.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.22.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.22.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.22.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.22.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.22.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.22.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.23.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.23.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.23.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.23.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.23.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.23.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.23.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.23.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.23.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.24.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.24.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.24.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.24.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.24.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.24.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.24.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.24.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.24.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.25.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.25.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.25.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.25.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.25.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.25.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.25.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.25.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.25.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.26.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.26.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.26.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.26.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.26.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.26.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.26.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.26.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.26.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.27.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.27.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.27.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.27.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.27.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.27.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.27.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.27.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.27.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.28.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.28.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.28.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.28.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.28.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.28.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.28.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.28.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.28.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.29.attn_norm.weight,     torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.29.ffn_down.weight,      torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.29.ffn_gate.weight,      torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.29.ffn_up.weight,        torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.29.ffn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.29.attn_k.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.29.attn_output.weight,   torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.29.attn_q.weight,        torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.29.attn_v.weight,        torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.3.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.3.ffn_down.weight,       torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.3.ffn_gate.weight,       torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.3.ffn_up.weight,         torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.3.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.3.attn_k.weight,         torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.3.attn_output.weight,    torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.3.attn_q.weight,         torch.float16 --> Q8_0, shape = {576, 576}
INFO:hf-to-gguf:blk.3.attn_v.weight,         torch.float16 --> Q8_0, shape = {576, 192}
INFO:hf-to-gguf:blk.4.attn_norm.weight,      torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.4.ffn_down.weight,       torch.float16 --> Q8_0, shape = {1536, 576}
INFO:hf-to-gguf:blk.4.ffn_gate.weight,       torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.4.ffn_up.weight,         torch.float16 --> Q8_0, shape = {576, 1536}
INFO:hf-to-gguf:blk.4.ffn_norm.weight,       torch.float16 --> F32, shape = {576}
INFO:hf-to-gguf:blk.4.attn_k.weight,         torch.float16 --> Q8_0, shape = {576, 192}


### Test the llama-cli

In [ ]:
!llama.cpp/llama-cli \
-m /kaggle/working/smolvlm_receipt_merged_f16.gguf \
--mmproj /kaggle/working/mmproj_smolvlm_receipt_merged_f16.gguf \
--image /kaggle/input/datasets/ahmadoubg/dataset-receipt/images/001.jpg \
-p "Extract company, date, address and total from this receipt.\nIf missing return null.\nDo NOT guess.\nReturn ONLY valid JSON."

Loading model... |-\|/-\ 


▄▄ ▄▄
██ ██
██ ██  ▀▀█▄ ███▄███▄  ▀▀█▄    ▄████ ████▄ ████▄
██ ██ ▄█▀██ ██ ██ ██ ▄█▀██    ██    ██ ██ ██ ██
██ ██ ▀█▄██ ██ ██ ██ ▀█▄██ ██ ▀████ ████▀ ████▀
                                    ██    ██
                                    ▀▀    ▀▀

build      : b9042-e3e3f8e46
model      : smolvlm_receipt_merged_f16.gguf
modalities : text, vision

available commands:
  /exit or Ctrl+C     stop or exit
  /regen              regenerate the last response
  /clear              clear the chat history
  /read <file>        add a text file
  /glob <pattern>     add text files using globbing pattern
  /image <file>       add an image file

Loaded media from '/kaggle/input/datasets/ahmadoubg/dataset-receipt/images/001.jpg'

> Extract company, date, address and total from this receipt.
If missing return null.
Do NOT guess.
Return ONLY valid JSON.

|-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|  { "company": "JOB MARKETING SDN BHD", "date": "02/01/2019", "address": "OJC MARKETING SDN BHD ROOC NO 538358 H", "total": "170.00".

[ Prompt: 22.4 t/s | Generation: 44.9 t/s ]

>


Exiting...
common_memory_breakdown_print: | memory breakdown [MiB] | total   free    self   model   context   compute    unaccounted |
common_memory_breakdown_print: |   - Host               |                  589 =   310 +     180 +      98                |

In [ ]:
# The generated output from llama.cpp was:
generated_response_llama_cpp = """
 { "company": "JOB MARKETING SDN BHD", "date": "02/01/2019", "address": "OJC MARKETING SDN BHD ROOC NO 538358 H", "total": "170.00"
 }
"""

# Find the ground truth for image 002.jpg in the dataset
gt_json_str_002 = None
for item in dataset:
    if item['img_path'] == '/kaggle/input/datasets/ahmadoubg/dataset-receipt/images/001.jpg':
        # Extract the assistant's response (ground truth JSON)
        full_text = item['full_text']
        gt_json_start_idx = full_text.find("Assistant:")
        if gt_json_start_idx != -1:
            gt_json_str_with_suffix = full_text[gt_json_start_idx + len("Assistant:"):].strip()
            gt_json_str_002 = gt_json_str_with_suffix.replace("<end_of_utterance>", "").strip()
        break

if gt_json_str_002 is None:
    print("Ground truth for 002.jpg not found in dataset.")
else:
    print(f"Ground Truth for 002.jpg: {gt_json_str_002}")
    print(f"Generated Response for 002.jpg: {generated_response_llama_cpp}")

    # Evaluate the sample
    result_llama_cpp = evaluate_sample(gt_json_str_002, generated_response_llama_cpp)

    print("-" * 40)
    print("EVALUATION (llama.cpp output for 002.jpg):")
    print(f"JSON Valid     : {result_llama_cpp['valid_json']}")
    print(f"Accuracy       : {result_llama_cpp['accuracy']*100:.2f}%")
    print(f"Precision      : {result_llama_cpp['precision']:.4f}")
    print(f"Recall         : {result_llama_cpp['recall']:.4f}")
    print(f"F1 Score       : {result_llama_cpp['f1']:.4f}")
    print(f"CER (global)   : {result_llama_cpp['cer']:.4f}")
    print(f"CER (fields)   : {result_llama_cpp['field_cer']:.4f}")
    print("-" * 40)

Ground Truth for 002.jpg: {"company": "OJC MARKETING SDN BHD", "date": "02/01/2019", "address": "NO 2 & 4, JALAN BAYU 4, BANDAR SERI ALAM, 81750 MASAI, JOHOR", "total": "170.00"}
Generated Response for 002.jpg:
 { "company": "JOB MARKETING SDN BHD", "date": "02/01/2019", "address": "OJC MARKETING SDN BHD ROOC NO 538358 H", "total": "170.00"
 }

----------------------------------------
EVALUATION (llama.cpp output for 002.jpg):
JSON Valid     : 1
Accuracy       : 85.71%
Precision      : 0.7500
Recall         : 1.0000
F1 Score       : 0.8571
CER (global)   : 0.3553
CER (fields)   : 0.2357
----------------------------------------